version: "3.9"

services:

    # Django: Backend
    django:
        image: smartsites-editor-platform:latest
        build: .
        container_name: smartsites-editor-platform
        command: bash ./start.sh ${MODE}
        restart: always
        ports:
            - 8000:8000
            - 3000:3000
        volumes:
            - .:/Website
        environment: 
            - MODE=${MODE}

    # ReactJS: Frontend Development Server
    # reactjs:
    #     build: .
    #     container_name: ReactJS
    #     command: npx npm start
    #     volumes:
    #         - .:/Website
    #     ports:
    #         - 3000:3000
    #     restart: always
    #     stdin_open: true

