# Generated by Django 4.0.1 on 2022-01-06 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(blank=True, default='', max_length=100, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('published', models.BooleanField(default=True, verbose_name='published')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tag', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('teaser', models.TextField(verbose_name='teaser')),
                ('body', models.TextField(verbose_name='body')),
                ('views', models.IntegerField(default=0, verbose_name='views')),
                ('average_note', models.FloatField(null=True, verbose_name='average_note')),
                ('commentable', models.BooleanField(default=True, verbose_name='commentable')),
                ('published_at', models.DateField(blank=True, verbose_name='published_at')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='category')),
                ('subcategory', models.CharField(blank=True, max_length=100, verbose_name='subcategory')),
                ('backlinks', models.JSONField(blank=True, default=list, verbose_name='backlinks')),
                ('notifications', models.JSONField(blank=True, default=list, verbose_name='notifications')),
                ('authors', models.JSONField(blank=True, default=list, verbose_name='authors')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='app.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='body')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created_at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author', verbose_name='author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
