# Generated by Django 4.0.1 on 2022-01-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_file_alter_image_options_image_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/files'),
        ),
    ]
