# Generated by Django 4.0.5 on 2022-07-27 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_file_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='page',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
