# Generated by Django 4.0.5 on 2022-07-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_image_rename_created_at_file_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
